---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
library(knitr)
library(ggplot2)
library(readxl)

SP <- read_excel("StudentsPerformance_G5_G6.xlsx")


knitr::opts_chunk$set(echo = TRUE)

#Lectura de base de datos



#Seleccion de columnas (variables) a estudiar
variables <-select(SP, "parental level of education", "lunch", "math score", "reading score", "writing score")
variables <- variables %>%
  mutate(Desempeño = round((`math score` + `reading score` + `writing score`) / 3,2 ))

notas <- select(SP, "math score", "reading score", "writing score")

notas <- notas %>%
  mutate(Desempeño = round((`math score` + `reading score` + `writing score`) / 3,2 ))
```


# distribucion de las variables cualitativas 

## column {data-width="600"}

### distribucion de la variable parental level of education 


```{r}
#Graficos de las Distribuciones de las variables cualitativas

Cantidad_parental_level <- variables %>%
  group_by(`parental level of education`) %>%
  summarise(
    Cantidad1 = n(),
    Proporcion1 = round((n() / nrow(variables)) * 100, 2)
  )
ggplot(Cantidad_parental_level, aes(x = `parental level of education`, y = Cantidad1, fill = `parental level of education`)) +
  geom_col() +
  labs(
    title = "Distribucion de la variable parental level of education",
    x = "Nivel de educacion parental",
    y = "Cantidad",
    fill = ""
  ) + theme_light() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    text = element_text(family = "serif"),
    legend.position = "bottom"
    )
```


## column {data-width="400"}

### DISTRIBUCION DE LA VARIABLE LUNCH

```{r}
Cantidad_lunch <- variables %>%
  group_by(`lunch`) %>%
  summarise(
    Cantidad2 = n(),
    Proporcion2 = round((n() / nrow(variables)) * 100, 2)
  )

kable(Cantidad_lunch,
      align = "c", 
      caption = "Distribución de la variable lunch")
      
ggplot(Cantidad_parental_level, aes(x = `parental level of education`, y = Cantidad1, fill = `parental level of education`)) +
  geom_col() +
  labs(
    title = "Distribucion de la variable parental level of education",
    x = "Nivel de educacion parental",
    y = "Cantidad",
    fill = ""
  ) + theme_light() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    text = element_text(family = "serif"),
    legend.position = "bottom"
    )

```




# Graficos de cajas 

## column {data-width="500"}

### grafico de caja 1
```{r}
ggplot(variables, aes(x = `lunch`, y = `Desempeño`, fill = `lunch`)) + 
  geom_boxplot() + 
  stat_summary(fun = "mean", geom = "point") + labs(
    title = "Desempeño en función de la Calidad de los Almuerzos", 
    x = "Almuerzo", 
    y = "Desempeño",
    fill = "") + theme(
    text = element_text(family = "serif"),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(hjust = 0.5))
```


## column {data-width="500"}

### grafico de caja 2
```{r}
ggplot(variables, aes(
  x = `parental level of education`, 
  y = Desempeño, 
  fill = `parental level of education`)) + 
  geom_boxplot() + 
  stat_summary(fun = "mean", geom = "point") + labs(
    title = "Desempeño en función del Nivel Educativo de los Padres", 
    x = "Nivel Educativo de los Padres", 
    y = "Desempeño",
    fill = "") + theme(
    text = element_text(family = "serif"),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(hjust = 0.5))
```


# pestana 3

## column 700



