---
title: "Prueba"
author: "Sofia"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    includes:
      in_header: preamble.tex
---

# Analisis Bivariante

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(readr)
library(dplyr)
library(knitr)
library(kableExtra)
library(plotly)

library(extrafont)
loadfonts(device = "win")

SP <- read.csv("C:/Users/PC/OneDrive/Documents/StudentsPerformance1.csv")
```


```{r Intervalos de "desempeño", echo=FALSE}
# Crear intervalos para Desempeño
SP$Desempeño_Intervalos <- cut(SP$Desempeño, 
                               breaks = c(9, 32, 55, 78, 100), 
                               right = FALSE,
                               include.lowest = TRUE,
                               labels = c("[9,32)", "[32,55)", "[55,78)", "[78,100]"))

```

```{r tabla1 , echo=FALSE}
# Crear la tabla de frecuencias bivariante a
tabla_frecuenciasa <- table(SP$parental_level_of_education, SP$Desempeño_Intervalos)
tabla_frecuenciasa <- addmargins(tabla_frecuenciasa)   # Añadir las frecuencias marginales
tabla_frecuenciasa_df <- as.data.frame.matrix(tabla_frecuenciasa) # Convertir la tabla a un data frame para formatearla

# Crear la tabla formateada
kable(tabla_frecuenciasa_df, caption = "Desempeño En Comparación al Nivel Educativo de los Padres", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "hold_position"))

# Reducir el espacio entre las tablas
invisible(capture.output(
  cat("\\vspace{-10mm}")
))  # Ajusta este valor para reducir el espacio entre las tablas
```

```{r grafico1, echo=FALSE, fig.width = 9, fig.height = 4}
ggplot(SP, aes(x = parental_level_of_education, y = Desempeño, fill = parental_level_of_education)) + geom_boxplot() + stat_summary(fun = "mean", geom = "point")  + labs(title = "Desempeño en función del Nivel Educativo de los Padres", x = "Nivel Educativo de los Padres", y = "Desempeño") + theme(text = element_text(family = "serif")) + theme(plot.title = element_text(hjust = 0.5)) + theme(axis.text.x = element_blank())
```


```{r tabla2 , echo=FALSE}
# Crear la tabla de frecuencias bivariante b
tabla_frecuenciasb <- table(SP$lunch, SP$Desempeño_Intervalos)
tabla_frecuenciasb <- addmargins(tabla_frecuenciasb)   # Añadir las frecuencias marginales
tabla_frecuenciasb_df <- as.data.frame.matrix(tabla_frecuenciasb) # Convertir la tabla a un data frame para formatearla

# Crear la tabla formateada
kable(tabla_frecuenciasb_df, caption = "Desempeño En Comparación al Tipo de Almuerzo", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

```{r grafico2, echo=FALSE, fig.width = 9, fig.height = 4}
ggplot(SP, aes(x = lunch, y = Desempeño, fill = lunch)) + geom_boxplot() + stat_summary(fun = "mean", geom = "point") + labs(title = "Desempeño en función del la Calidad de los Almuerzos", x = "Almuerzo", y = "Desempeño") +  theme(text = element_text(family = "serif")) + theme(text = element_text(family = "serif")) + theme(plot.title = element_text(hjust = 0.5)) + theme(axis.text.x = element_blank())
```

```{r grafico3, echo=FALSE, fig.width = 9, fig.height = 4}
ggplot(SP, aes(x = parental_level_of_education, y = Desempeño, fill = lunch)) + geom_boxplot() + stat_summary(fun = "mean", geom = "point", position = position_dodge(width = 0.75))  + labs(title = "Desempeño en función del Nivel Educativo de los Padres", x = "Nivel Educativo de los Padres", y = "Desempeño") + theme(text = element_text(family = "serif")) + theme(plot.title = element_text(hjust = 0.5)) + theme(axis.text.x = element_blank())             
```

